# Generated by Django 2.0.5 on 2018-05-12 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100, null=True, unique=True)),
                ('description', models.CharField(default=None, max_length=200, null=True)),
                ('run_interval', models.IntegerField(default=0, null=True)),
                ('rule_data', models.TextField(default=None, null=True)),
                ('extra', models.CharField(default=None, max_length=200, null=True)),
                ('status', models.IntegerField(default=0, null=True)),
                ('last_run_time', models.DateTimeField(null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('uid', models.CharField(default=None, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'seed',
                'verbose_name_plural': 'seed',
                'db_table': 'vertical_crawler_seed',
            },
        ),
    ]
